version: "2"
linters:
  default: all
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    #- cyclop
    - decorder
    #- depguard
    - dogsled
    #- dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    #- exhaustruct
    - exptostd
    - fatcontext
    #- forbidigo
    - forcetypeassert
    #- funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    #- gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    #- gocyclo
    #- godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    #- intrange
    #- ireturn
    #- lll
    - loggercheck
    #- maintidx
    - makezero
    - mirror
    - misspell
    #- mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    #- nlreturn
    - noctx
    - nolintlint
    #- nonamedreturns
    - nosprintfhostport
    #- paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    #- revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    #- varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    #- wsl
    - zerologlint
  disable:
    - cyclop
    - depguard
    - dupl
    - exhaustruct
    - intrange
    - ireturn
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocyclo
    - godot
    - lll
    - maintidx
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - revive
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    nestif:
      min-complexity: 10
  # exclusions:
#formatters:
#  enable:
#    - gofmt
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
# output:
run:
  concurrency: 1
  timeout: 30m
  issues-exit-code: 1
  relative-path-mode: gomod
  modules-download-mode: readonly
  allow-parallel-runners: false
  tests: true
# severity:
