name: shortlinkcommit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: StyleChecker
      run: go fmt ./...
        
    - name: Linter
      uses: golangci/golangci-lint-action@v3
      with:
          version: v1.51.2
                
    - name: UnitTests
      run: go test -vet=off -count=1 -race ./...

    - name: Build
      run: go build -o ./bin/shortlink ./cmd/main.go
