name: shortlink-commit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
          go-version: 1.21

    - name: StyleChecker
      run: go fmt ./...
        
    - name: Linter
      uses: golangci/golangci-lint-action@v3
      with:
          version: v1.51.2
          args: --config=./config/.golangci.yaml
                
    - name: UnitTests
      run: go test -short -tags go_tarantool_ssl_disable -vet=off -count=1 -race ./...

    - name: Build
      run: go build -tags go_tarantool_ssl_disable -o ./bin/shortlink ./cmd/main.go

    - name: StartServer
      run: ./bin/shortlink &

    - name: URL Health Check
      uses: Jtalk/url-health-check-action@v3.1
      with:
          url: http://localhost:8080/check/ping
